/**
 * Test fixtures for e2e tests.
 *
 * When a real test fixture exists (generated by `bun run eth_balance:prove`),
 * we use the real proof, state root, and public inputs from it.
 * Otherwise we fall back to mock fixtures with module-level verifyProof mocking.
 */

import { existsSync, readFileSync } from "fs";
import { resolve } from "path";

const FIXTURE_PATH = resolve(
  process.cwd(),
  "packages/circuits/bin/eth_balance/target/test-fixture.json",
);

/** Whether a real proof fixture is available. */
export const HAS_REAL_FIXTURE = existsSync(FIXTURE_PATH);

interface TestFixture {
  proof: string;
  publicInputs: string[];
  stateRoot: string;
  epoch: number;
  minBalance: string;
  nullifier: string;
}

let cachedFixture: TestFixture | null = null;

function loadFixture(): TestFixture | null {
  if (!HAS_REAL_FIXTURE) return null;
  if (cachedFixture) return cachedFixture;
  cachedFixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8"));
  return cachedFixture;
}

/** A valid proof hex string. Real proof if fixture exists, mock otherwise. */
export function getValidProof(): string {
  const fixture = loadFixture();
  if (fixture) return fixture.proof;
  return (
    "0xdeadbeefcafebabe0123456789abcdef" +
    "deadbeefcafebabe0123456789abcdef"
  );
}

/** An empty proof that verifiers will reject. */
export const INVALID_PROOF = "0x";

/** A valid Ethereum address to receive testnet funds. */
export const TEST_RECIPIENT = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8";

/** The target network for test claims. */
export const TEST_NETWORK = "sepolia";

/** Module ID for the eth-balance proof module. */
export const MODULE_ID = "eth-balance:1";

/** Minimum balance in wei matching the server constant (0.01 ETH). */
export const MIN_BALANCE_WEI = "10000000000000000";

/** A state root that the test oracle accepts. Real root from fixture if available. */
export function getValidStateRoot(): string {
  const fixture = loadFixture();
  if (fixture) return fixture.stateRoot;
  return (
    "0x00000000000000000000000000000000" +
    "00000000000000000000000000000001"
  );
}

/**
 * A stale state root that is NOT in the oracle cache, simulating a root
 * from more than 256 blocks ago.
 */
export const STALE_STATE_ROOT =
  "0xffffffffffffffffffffffffffffffff" +
  "ffffffffffffffffffffffffffffffff";

let nullifierCounter = 0;

/**
 * Generate a unique nullifier for each test to avoid cross-test interference
 * from the nullifier deduplication store.
 */
export function uniqueNullifier(): string {
  nullifierCounter++;
  const hex = nullifierCounter.toString(16).padStart(64, "0");
  return "0x" + hex;
}

/**
 * Get the fixture's nullifier if available (real proofs use a specific nullifier).
 */
export function getFixtureNullifier(): string | null {
  const fixture = loadFixture();
  return fixture?.nullifier ?? null;
}

/**
 * Get the fixture's epoch if available.
 */
export function getFixtureEpoch(): number | null {
  const fixture = loadFixture();
  return fixture?.epoch ?? null;
}

/**
 * Build valid public inputs for a claim request. Uses the current epoch
 * from the module and the valid (seeded) state root.
 */
export function validPublicInputs(
  epoch: number,
  overrides: Partial<{
    stateRoot: string;
    minBalance: string;
    nullifier: string;
  }> = {},
) {
  return {
    stateRoot: overrides.stateRoot ?? getValidStateRoot(),
    epoch,
    minBalance: overrides.minBalance ?? MIN_BALANCE_WEI,
    nullifier: overrides.nullifier ?? uniqueNullifier(),
  };
}

/**
 * Build a full claim request body.
 */
export function claimBody(
  epoch: number,
  overrides: Partial<{
    moduleId: string;
    proof: string;
    stateRoot: string;
    minBalance: string;
    nullifier: string;
    recipient: string;
    targetNetwork: string;
  }> = {},
) {
  const pi = validPublicInputs(epoch, {
    stateRoot: overrides.stateRoot,
    minBalance: overrides.minBalance,
    nullifier: overrides.nullifier,
  });

  return {
    moduleId: overrides.moduleId ?? MODULE_ID,
    proof: overrides.proof ?? getValidProof(),
    publicInputs: pi,
    recipient: overrides.recipient ?? TEST_RECIPIENT,
    targetNetwork: overrides.targetNetwork ?? TEST_NETWORK,
  };
}
